swagger: '2.0'
info:
  title: kgd App api
  description: 'kgd App api swagger文档'
  termsOfService: ''
  contact:
    email: sales@techrare.com
  version: 1.0.0
#host: '192.168.1.108'
#basePath: /wopinapi3/public/api/app
host: '127.0.0.1'
basePath: /wopinappapi/public/api
$ref#common: "./common.yaml"